import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{createPortal}from"react-dom";
import{AnimatePresence,motion}from"framer-motion";
import{ArrowLeft,ArrowRight,Award,Check,ChevronDown,GitMerge,Menu,MessageCircle,RefreshCw,Settings,Sparkles,Target,Volume2,VolumeX,X,Zap}from"lucide-react";
import"./styles.css";
import hero from"./assets/illustrations/merger-disruption-v2.png";
import restructure from"./assets/illustrations/restructure.png";
import merger from"./assets/illustrations/merger-acquisition.png";
import technology from"./assets/illustrations/technology-shift.png";
import strategy from"./assets/illustrations/strategy-leadership.png";
import resistance from"./assets/illustrations/resistance.png";
import communication from"./assets/illustrations/change-communication.png";
import governance from"./assets/illustrations/governance-boundary.png";
import throughline from"./assets/illustrations/module-throughline.png";
import resolved from"./assets/illustrations/resolved-timeline.png";

const screens=["The disruption","Evaluate the shift","Manage the human side","Authority boundary","Module throughline","Exam lens"];
const shifts=[
 {name:"Restructure",image:restructure,kicker:"REPORTING LINES MOVE",text:"A restructure can redraw reporting lines overnight. The project may inherit a new sponsor, altered decision paths, or a different team composition. Reconfirm ownership, authority, and working relationships before assuming yesterday’s governance still applies."},
 {name:"Merger or acquisition",image:merger,kicker:"THE BUSINESS CASE MOVES",text:"A merger can introduce new priorities, systems, and definitions of value. Reassess the project against the combined organization’s strategy and determine whether its original business case still holds."},
 {name:"Technology shift",image:technology,kicker:"TOOLS AND SKILLS MOVE",text:"A new platform or tool can change scope, delivery methods, integration needs, and the skills required to complete the work. Evaluate the practical project impact rather than classifying only the leadership event that triggered it."},
 {name:"Strategy or leadership change",image:strategy,kicker:"THE DESTINATION MAY MOVE",text:"New leadership can reset organizational direction. The project must be tested honestly against the new strategy—including whether it still delivers the value it was authorized to deliver."}
];
const q1={q:"A new CTO mandates a different project-management software platform mid-project. Which change pattern is this?",answers:["Restructure","Merger or acquisition","Technology shift","Strategy or leadership change"],correct:2,yes:"Right—the project-level impact is a new platform and tooling environment.",no:"Look at what actually changed for the project: its platform and tools."};
const q2={q:"After an acquisition, a stakeholder asks whether the project is still a strategic priority and who owns it. What should the PM do?",answers:["Answer from personal judgment to preserve momentum","Escalate to the sponsor or steering committee","Ignore it until a formal steering meeting","Pause all work immediately"],correct:1,yes:"Right—strategic priority and ownership sit above the PM’s authority.",no:"This is a strategic ownership decision, not a plan adjustment within the PM’s remit."};

function Modal({detail,onClose,onRead}){useEffect(()=>{const f=e=>e.key==="Escape"&&onClose();addEventListener("keydown",f);return()=>removeEventListener("keydown",f)},[onClose]);return createPortal(<motion.div className="modal-backdrop focused-modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose}><motion.section className="detail-sheet detail-modal" initial={{opacity:0,y:24,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:15,scale:.98}} onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={onClose}><X/></button>{detail.image&&<img className="drawer-illustration" src={detail.image} alt=""/>}<p className="mini-label">{detail.kicker}</p><h3>{detail.name||detail.title}</h3><p>{detail.text}</p>{detail.note&&<div className="sheet-note"><Target/><span>{detail.note}</span></div>}<button className="modal-close-bottom" onClick={()=>{onRead?.();onClose()}}>{detail.action||"Mark as read"}<Check/></button></motion.section></motion.div>,document.body)}
function Quiz({data,onFinish}){const[pick,setPick]=useState(null);return createPortal(<div className="knowledge-modal-backdrop"><motion.section className="quiz knowledge-modal" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><p className="quiz-label"><Target/> MICRO KNOWLEDGE CHECK</p><h3>{data.q}</h3><div className="answers">{data.answers.map((a,i)=><button key={a} className={pick===i?(i===data.correct?"correct":"wrong"):""} onClick={()=>setPick(i)}><span>{String.fromCharCode(65+i)}</span>{a}</button>)}</div>{pick!==null&&<p className={pick===data.correct?"feedback good":"feedback bad"}>{pick===data.correct?data.yes:`${data.no} Choose another answer to try again.`}</p>}{pick===data.correct&&<button className="finish-check" onClick={onFinish}>Finish check <ArrowRight/></button>}</motion.section></div>,document.body)}

function App(){const[page,setPage]=useState(0),[sound,setSound]=useState(true),[menu,setMenu]=useState(false),[detail,setDetail]=useState(null),[heroRead,setHeroRead]=useState(false),[seen,setSeen]=useState([]),[quiz,setQuiz]=useState(null),[qOne,setQOne]=useState(false),[flips,setFlips]=useState([]),[tab,setTab]=useState(0),[tabsSeen,setTabsSeen]=useState([]),[qTwo,setQTwo]=useState(false),[arc,setArc]=useState(false),[done,setDone]=useState(false);
 const can=[heroRead,seen.length===4&&qOne,flips.length===2,tabsSeen.length===2&&qTwo,arc,done][page];
 const next=()=>{if(page<5)setPage(page+1)};
 const openShift=i=>setDetail({...shifts[i],index:i});
 const readDetail=()=>{if(detail?.index!==undefined)setSeen(v=>v.includes(detail.index)?v:[...v,detail.index])};
 return <div className="app-shell"><header className="topbar"><button className="course-select"><Award/><span>PMP Project Management Professional</span><ChevronDown/></button><div className="module-progress"><div>{Array.from({length:10},(_,i)=><span key={i} className={`progress-dot ${i<9?"done":i===9?"active":""}`}>{i<9?<Check size={10}/>:<span/>}</span>)}</div></div><div className="top-actions"><button className="ghost-button" onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}<span>{sound?"Sound on":"Sound off"}</span></button><button className="ghost-button"><X/><span>Quit</span></button></div></header><main className="workspace"><section className="lesson-stage"><div className="outline"><button className="menu-button" aria-label="Open lesson outline" onClick={()=>setMenu(!menu)}><Menu/></button>{menu&&<div className="outline-panel"><div className="outline-summary"><div><b>Lesson progress</b><span>{page+1} / 6</span></div><span className="summary-track"><span style={{width:`${((page+1)/6)*100}%`}}/></span></div><div className="study-block"><div className="study-heading"><span><span className="block-status">3</span> Organizational change</span></div><div className="lesson-list">{screens.map((s,i)=><button key={s} className={`lesson ${i===page?"current":""}`} disabled={i>page} onClick={()=>{setPage(i);setMenu(false)}}><span>{i<page?<Check size={13}/>:i+1}</span><span>{s}</span><small>{i<page?"Read":i===page?"Current":"Locked"}</small></button>)}</div></div></div>}</div><article className="lesson-card"><nav className="section-tabs"><p className="section-tabs-count">Section {page+1} of 6</p><div className="section-tabs-row">{screens.map((s,i)=><button key={s} disabled={i>page} className={`section-tab ${i===page?"active":i<page?"done":"locked"}`} onClick={()=>setPage(i)}>{i<page&&<Check/>}<span>{s}</span></button>)}</div></nav><AnimatePresence mode="wait"><motion.section key={page} className="lesson-content change-page" initial={{opacity:0,x:44}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-30}}>
 {page===0&&<div className="change-hero"><div><p className="eyebrow">LESSON 3.5.2 · ORGANIZATIONAL CHANGE</p><p className="lesson-name">Evaluate the Impact of Organizational Change on the Project and Determine Required Actions</p><h1>The plan was steady.<br/><em>Then the organization moved.</em></h1><p>Four months of clear progress. Then a merger closes over the weekend. By Wednesday, your sponsor’s title has changed—and someone new is quietly asking why the project still exists.</p><button className="primary compact-cta" onClick={()=>setDetail({title:"The moving context",kicker:"EVALUATE BEFORE YOU REACT",image:hero,text:"Culture is the standing context a project operates within; this enabler is about the moving one. Restructures, mergers, new platforms, and leadership changes may never appear in the schedule, yet they can reshape what the project needs, who it answers to, or whether it should continue.",note:"Neither panic nor denial is professional. Determine how the change affects the project, then determine what action it requires.",action:"Continue"})}>Reveal the project impact <ArrowRight/></button></div><img className="change-art" src={hero} alt="A project team faces a new sponsor after a merger changes the organization"/></div>}
 {page===1&&<div className="wide"><p className="eyebrow">FOUR ORGANIZATIONAL SHIFTS</p><h2>Same disruption. Different project impact.</h2><p className="lede">Open each change type. Evaluate what actually moved for the project.</p><div className="direct-card-grid">{shifts.map((s,i)=><button key={s.name} className={`direct-detail-card ${seen.includes(i)?"visited":""}`} onClick={()=>openShift(i)}><img src={s.image} alt=""/><span className="direct-card-copy"><small>{seen.includes(i)?<><Check/> READ</>:`0${i+1}`}</small><strong>{s.name}</strong></span><ArrowRight/></button>)}</div>{seen.length===4&&<div className="two-question"><div><b>01</b><span>How does this affect the project?</span></div><div><b>02</b><span>What action does it require?</span></div></div>}{seen.length===4&&!qOne&&<button className="knowledge-check-cta" onClick={()=>setQuiz(q1)}><Target/> Start knowledge check <ArrowRight/></button>}</div>}
 {page===2&&<div className="wide"><p className="eyebrow">MANAGING CHANGE AT PROJECT LEVEL</p><h2>Uncertainty makes two familiar skills essential.</h2><p className="lede">Each illustration belongs to its card. Flip both text panels.</p><div className="flip-grid">{[{name:"Anticipate and address resistance",image:resistance,text:"Identify who is affected, surface their concerns, and move resistant stakeholders toward support rather than overruling them. Resistance is information—often an unaddressed expectation or fear—not obstruction for its own sake."},{name:"Communicate steadily",image:communication,text:"Clear, frequent, honest communication through the communication plan is the strongest tool for carrying people through change. People resist what they do not understand and fear what they cannot see."}].map((f,i)=><div className="illustrated-flip" key={f.name}><img className="flip-card-art" src={f.image} alt=""/><button className={`flip ${flips.includes(i)?"flipped":""}`} onClick={()=>setFlips(v=>v.includes(i)?v:[...v,i])}><div className="flip-inner"><div className="flip-front"><small>CLICK TO FLIP</small><h3>{f.name}</h3></div><div className="flip-back"><small>CHANGE PRACTICE</small><h3>{f.name}</h3><p>{f.text}</p></div></div></button></div>)}</div>{flips.length===2&&<div className="backing">Project-level change management is stakeholder engagement and communication applied under uncertainty. Honest information must fill the space before rumours do.</div>}</div>}
 {page===3&&<div className="governance-screen"><div><p className="eyebrow">CONNECT CHANGE TO GOVERNANCE</p><h2>Act within authority. Escalate beyond it.</h2><p className="lede">Select both states to see where the line sits.</p><div className="mode-tabs"><button className={tab===0?"active":""} onClick={()=>{setTab(0);setTabsSeen(v=>v.includes(0)?v:[...v,0])}}><Settings/> Manage within authority</button><button className={tab===1?"active":""} onClick={()=>{setTab(1);setTabsSeen(v=>v.includes(1)?v:[...v,1])}}><ArrowRight/> Escalate beyond it</button></div><motion.div className="authority-copy" key={tab} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}>{tab===0?<><h3>Absorb the operational change.</h3><p>Adapt the plan, re-engage stakeholders, and adjust communications when those actions sit within the PM’s remit.</p></>:<><h3>Surface the strategic decision.</h3><p>Questions about continuing priority, sponsorship, ownership, or business justification belong to the sponsor or steering committee. Prompt escalation is disciplined governance—not failure.</p></>}</motion.div>{tabsSeen.length===2&&!qTwo&&<button className="knowledge-check-cta" onClick={()=>setQuiz(q2)}><Target/> Start knowledge check <ArrowRight/></button>}</div><img className="governance-art" src={governance} alt="Operational changes remain with the PM while strategic questions rise to governance"/></div>}
 {page===4&&<div className="throughline"><p className="eyebrow">THE MODULE 3 THROUGHLINE</p><h2>A project manager reads reality before acting in it.</h2><img src={throughline} alt="Business need, vision, stakeholders, and organizational change connected across Module 3"/><button className="primary compact-cta" onClick={()=>setArc(true)}>{arc?"Module arc revealed":"Reveal the shared skill"}<Sparkles/></button>{arc&&<motion.div className="throughline-copy" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><p>Initiation read the business need. Vision work read what could unite the team. Stakeholder work read who mattered and what they truly expected. This lesson reads the organization and the changes moving through it.</p><p><b>The underlying skill is constant:</b> perceive human and organizational reality accurately, then act deliberately within it. Being blindsided is often not bad luck—it is context that was available but never read.</p></motion.div>}</div>}
 {page===5&&<div className="exam change-exam"><img src={resolved} alt="A disrupted project timeline is deliberately rerouted and continues forward"/><div><p className="eyebrow">EXAM LENS · MODULE 3 COMPLETE</p><h2>When the organization shifts, evaluate before you react.</h2><p className="exam-intro">Determine the project impact, choose the required action, manage the human response, and escalate decisions that genuinely sit above your authority.</p><button className="primary compact-cta" onClick={()=>setDone(true)}>{done?"Module 3 complete":"Reveal the exam rules"}<Sparkles/></button>{done&&<ul><li>Evaluate restructure, merger, technology, and strategy changes separately.</li><li>Ask: how does this affect the project, and what action does it require?</li><li>Treat resistance as information; use honest communication to reduce fear.</li><li>Manage within authority and escalate strategic ownership decisions.</li><li>This completes ECO Business Environment Task 7 and Module 3.</li></ul>}</div></div>}
 </motion.section></AnimatePresence>{can&&<div className="anchor"><Check/> Interaction complete — continue when ready.</div>}<footer className="nav-footer"><button className="secondary-button" disabled={page===0} onClick={()=>setPage(page-1)}><ArrowLeft/> Previous</button><button className={`primary-button ${can?"unlocked":""}`} disabled={!can} onClick={next}>{page===5?"Continue to Module 4":"Continue"}<ArrowRight/></button></footer></article></section></main><AnimatePresence>{detail&&<Modal detail={detail} onClose={()=>setDetail(null)} onRead={()=>{if(page===0)setHeroRead(true);readDetail()}}/>}</AnimatePresence>{quiz&&<Quiz data={quiz} onFinish={()=>{if(quiz===q1)setQOne(true);else setQTwo(true);setQuiz(null)}}/>}</div>}
createRoot(document.getElementById("root")).render(<App/>);
