import React,{useEffect,useState}from"react";
import{createRoot}from"react-dom/client";
import{createPortal}from"react-dom";
import{AnimatePresence,motion}from"framer-motion";
import{ArrowLeft,ArrowRight,Award,Check,ChevronDown,GitMerge,Menu,MessageCircle,RefreshCw,Settings,Sparkles,Target,Volume2,VolumeX,X,Zap}from"lucide-react";
import"./styles.css";
import hero from"./assets/illustrations/merger-disruption-v2.png";
import restructure from"./assets/illustrations/restructure.png";
import merger from"./assets/illustrations/merger-acquisition.png";
import technology from"./assets/illustrations/technology-shift.png";
import strategy from"./assets/illustrations/strategy-leadership.png";
import resistance from"./assets/illustrations/resistance.png";
import communication from"./assets/illustrations/change-communication.png";
import governance from"./assets/illustrations/governance-boundary.png";
import throughline from"./assets/illustrations/module-throughline.png";
import resolved from"./assets/illustrations/resolved-timeline.png";

const screens=["The disruption","Evaluate the shift","Manage the human side","Authority boundary","Module throughline","Exam lens"];
const shifts=[
 {name:"Restructure",image:restructure,kicker:"ORGANIZATIONAL SHIFT 01",text:"Can redraw reporting lines — which means the project's sponsor or even its team composition may change overnight."},
 {name:"Merger or Acquisition",image:merger,kicker:"ORGANIZATIONAL SHIFT 02",text:"Can bring new priorities and new systems into the organization — which means the project may need to be re-justified against a business case that no longer fully applies."},
 {name:"Technology Shift",image:technology,kicker:"ORGANIZATIONAL SHIFT 03",text:"Can introduce new platforms or tools — affecting the project's scope and the skills required to deliver it."},
 {name:"Strategy or Leadership Change",image:strategy,kicker:"ORGANIZATIONAL SHIFT 04",text:"Can reset organizational direction entirely — prompting a genuine reassessment of whether the project still delivers the value it was authorized to deliver."}
];
const q1={q:"Scenario: A new CTO joins the organization and mandates a shift to a different project management software platform mid-project. Which type of organizational change is this?",answers:["Restructure","Merger or acquisition","Technology shift","Strategy or leadership change"],correct:2,yes:"Right — new platforms or tools introduced into the project's environment is the technology-shift pattern, even when a leadership change is what triggered it.",no:"Look at what actually changed for the project — it's the tooling and platform, not the reporting lines or the business case."};
const q2={q:"Scenario: Following an acquisition, a stakeholder asks whether the project is still the organization's strategic priority and who owns it going forward. What should the project manager do?",answers:["Answer based on their own read of the situation to keep momentum going","Escalate the question to the sponsor or steering committee — this decision sits above the PM's authority","Ignore the question until it's raised formally in a steering meeting","Pause the project entirely until the acquisition dust settles"],correct:1,yes:"Right — \"is this still our priority, and who owns it\" is a strategic ownership question that belongs to the sponsor or steering committee, not something the PM should decide or guess at alone.",no:"Reconsider — this specific question sits above what a PM manages within their own authority."};

function Modal({detail,onClose,onRead}){useEffect(()=>{const f=e=>e.key==="Escape"&&onClose();addEventListener("keydown",f);return()=>removeEventListener("keydown",f)},[onClose]);return createPortal(<motion.div className="modal-backdrop focused-modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose}><motion.section className="detail-sheet detail-modal" initial={{opacity:0,y:24,scale:.97}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:15,scale:.98}} onClick={e=>e.stopPropagation()}><button className="drawer-close" onClick={onClose}><X/></button>{detail.image&&<img className="drawer-illustration" src={detail.image} alt=""/>}<p className="mini-label">{detail.kicker}</p><h3>{detail.name||detail.title}</h3><p>{detail.text}</p>{detail.note&&<div className="sheet-note"><Target/><span>{detail.note}</span></div>}<button className="modal-close-bottom" onClick={()=>{onRead?.();onClose()}}>{detail.action||"Mark as read"}<Check/></button></motion.section></motion.div>,document.body)}
function Quiz({data,onFinish}){const[pick,setPick]=useState(null);return createPortal(<div className="knowledge-modal-backdrop"><motion.section className="quiz knowledge-modal" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><p className="quiz-label"><Target/> MICRO KNOWLEDGE CHECK</p><h3>{data.q}</h3><div className="answers">{data.answers.map((a,i)=><button key={a} className={pick===i?(i===data.correct?"correct":"wrong"):""} onClick={()=>setPick(i)}><span>{String.fromCharCode(65+i)}</span>{a}</button>)}</div>{pick!==null&&<p className={pick===data.correct?"feedback good":"feedback bad"}>{pick===data.correct?data.yes:data.no}</p>}{pick!==null&&<button className="finish-check" onClick={onFinish}>Finish check <ArrowRight/></button>}</motion.section></div>,document.body)}

function App(){const[page,setPage]=useState(0),[sound,setSound]=useState(true),[menu,setMenu]=useState(false),[detail,setDetail]=useState(null),[heroRead,setHeroRead]=useState(false),[seen,setSeen]=useState([]),[quiz,setQuiz]=useState(null),[qOne,setQOne]=useState(false),[flips,setFlips]=useState([]),[tab,setTab]=useState(0),[tabsSeen,setTabsSeen]=useState([]),[qTwo,setQTwo]=useState(false),[arc,setArc]=useState(false),[done,setDone]=useState(false);
 const can=[heroRead,seen.length===4&&qOne,flips.length===2,tabsSeen.length===2&&qTwo,arc,done][page];
 const next=()=>{if(page<5)setPage(page+1)};
 const openShift=i=>setDetail({...shifts[i],index:i});
 const readDetail=()=>{if(detail?.index!==undefined)setSeen(v=>v.includes(detail.index)?v:[...v,detail.index])};
 return <div className="app-shell"><header className="topbar"><button className="course-select"><Award/><span>PMP Project Management Professional</span><ChevronDown/></button><div className="module-progress"><div>{Array.from({length:10},(_,i)=><span key={i} className={`progress-dot ${i<9?"done":i===9?"active":""}`}>{i<9?<Check size={10}/>:<span/>}</span>)}</div></div><div className="top-actions"><button className="ghost-button" onClick={()=>setSound(!sound)}>{sound?<Volume2/>:<VolumeX/>}<span>{sound?"Sound on":"Sound off"}</span></button><button className="ghost-button"><X/><span>Quit</span></button></div></header><main className="workspace"><section className="lesson-stage"><div className="outline"><button className="menu-button" aria-label="Open lesson outline" onClick={()=>setMenu(!menu)}><Menu/></button>{menu&&<div className="outline-panel"><div className="outline-summary"><div><b>Lesson progress</b><span>{page+1} / 6</span></div><span className="summary-track"><span style={{width:`${((page+1)/6)*100}%`}}/></span></div><div className="study-block"><div className="study-heading"><span><span className="block-status">3</span> Organizational change</span></div><div className="lesson-list">{screens.map((s,i)=><button key={s} className={`lesson ${i===page?"current":""}`} disabled={i>page} onClick={()=>{setPage(i);setMenu(false)}}><span>{i<page?<Check size={13}/>:i+1}</span><span>{s}</span><small>{i<page?"Read":i===page?"Current":"Locked"}</small></button>)}</div></div></div>}</div><article className="lesson-card"><nav className="section-tabs"><p className="section-tabs-count">Section {page+1} of 6</p><div className="section-tabs-row">{screens.map((s,i)=><button key={s} disabled={i>page} className={`section-tab ${i===page?"active":i<page?"done":"locked"}`} onClick={()=>setPage(i)}>{i<page&&<Check/>}<span>{s}</span></button>)}</div></nav><AnimatePresence mode="wait"><motion.section key={page} className="lesson-content change-page" initial={{opacity:0,x:44}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-30}}>
 {page===0&&<div className="change-hero"><div><p className="eyebrow">LESSON 3.5.2</p><p className="lesson-name">Evaluate the Impact of Organizational Change on the Project and Determine Required Actions</p><h1>Evaluate the Impact of Organizational Change on the Project and Determine Required Actions</h1><p>Picture this: you've been running a project for four months. Steady progress, clear plan, no surprises. Monday morning, an all-hands email announces a merger finalized over the weekend. Nothing in your project charter mentioned this. By Wednesday, your sponsor's title has changed — and someone new is quietly asking why the project still exists.</p><button className="primary compact-cta" onClick={()=>setDetail({title:"Evaluate before you react",kicker:"CLICK-TO-REVEAL",image:hero,text:"Culture is the standing context a project operates within. This enabler is about the moving one. A restructure gets announced. A merger is finalized. New leadership takes over with a different strategic direction. None of these show up as a line item in your project schedule — and yet each one can reshape what your project needs, who it answers to, or whether it should continue at all. The instinct many project managers have is to treat this as either a crisis or a non-event — panic and freeze, or ignore it and hope the project plan absorbs the shock. Neither is the professional response. This enabler asks for something more deliberate.",action:"Continue"})}>Reveal the project impact <ArrowRight/></button></div><div className="hero-image-motion"><img className="change-art" src={hero} alt="A project team faces a new sponsor after a merger changes the organization"/></div></div>}
 {page===1&&<div className="wide"><p className="eyebrow">WHAT THIS ENABLER MEANS</p><h2>Four different kinds of organizational shift can hit a project</h2><p className="lede">Four different kinds of organizational shift can hit a project, and each one lands differently. Click each to see how.</p><div className="direct-card-grid">{shifts.map((s,i)=><button key={s.name} className={`direct-detail-card ${seen.includes(i)?"visited":""}`} onClick={()=>openShift(i)}><img src={s.image} alt=""/><span className="direct-card-copy"><small>{seen.includes(i)?<><Check/> READ</>:`0${i+1}`}</small><strong>{s.name}</strong></span><ArrowRight/></button>)}</div>{seen.length===4&&<><div className="two-question"><div><b>01</b><span>How does this affect the project?</span></div><div><b>02</b><span>What action does it require?</span></div></div><p className="canonical-callout">For each of these, the project manager asks two questions, every time: How does this affect the project? And what action does it require? A merger or a new executive is not automatically a stop sign. It is a prompt — to ask how it actually hits the project, and what the appropriate response is.</p></>}{seen.length===4&&!qOne&&<button className="knowledge-check-cta" onClick={()=>setQuiz(q1)}><Target/> Start knowledge check <ArrowRight/></button>}</div>}
 {page===2&&<div className="wide"><p className="eyebrow">MANAGING CHANGE AT THE PROJECT LEVEL</p><h2>Managing Change at the Project Level</h2><p className="lede">Beyond reacting to change coming from outside the project, the PM also actively manages the human side of change the project itself creates. That work rests on two pillars — both building directly on skills from earlier in this module. Flip both cards to see them.</p><div className="flip-grid">{[{name:"Anticipating and Addressing Resistance",image:resistance,text:"Drawing on the stakeholder engagement work from Lessons 3.3 and 3.4, the PM identifies who is affected by a given change, surfaces their concerns, and works to move resistant stakeholders toward support — rather than simply overruling them. Resistance is information, usually an unaddressed expectation or fear, not obstruction for its own sake."},{name:"Communication",image:communication,text:"Clear, frequent, honest communication, delivered through the project's communication plan, is the single most powerful tool for carrying people through change. People resist what they don't understand and fear what they can't see. A steady flow of relevant information reduces both."}].map((f,i)=><div className="illustrated-flip" key={f.name}><img className="flip-card-art" src={f.image} alt=""/><button className={`flip ${flips.includes(i)?"flipped":""}`} onClick={()=>setFlips(v=>v.includes(i)?v:[...v,i])}><div className="flip-inner"><div className="flip-front"><small>CLICK TO FLIP</small><h3>{f.name}</h3></div><div className="flip-back"><small>CHANGE PRACTICE</small><h3>{f.name}</h3><p>{f.text}</p></div></div></button></div>)}</div>{flips.length===2&&<div className="backing">In practice, change management at the project level is largely stakeholder engagement and communication, applied under conditions of uncertainty rather than stability. In change, communication is your strongest tool — a steady flow of honest information beats the rumours that will otherwise fill any silence.</div>}</div>}
 {page===3&&<div className="governance-screen"><div><p className="eyebrow">CONNECTING CHANGE TO GOVERNANCE</p><h2>Connecting Change to Governance</h2><p className="lede">Not every change is the project manager's to resolve alone. This is where the enabler connects directly back to the governance work from Lessons 2.4 and 3.1. Toggle between the two to see where the line sits.</p><div className="mode-tabs"><button className={tab===0?"active":""} onClick={()=>{setTab(0);setTabsSeen(v=>v.includes(0)?v:[...v,0])}}><Settings/> Manage Within Authority</button><button className={tab===1?"active":""} onClick={()=>{setTab(1);setTabsSeen(v=>v.includes(1)?v:[...v,1])}}><ArrowRight/> Escalate Beyond It</button></div><motion.div className="authority-copy" key={tab} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}}>{tab===0?<><h3>Manage Within Authority</h3><p>The project manager manages change within their own authority — adapting the plan, re-engaging stakeholders, adjusting communications. This is the day-to-day absorption of change that doesn't require anyone else's decision.</p></>:<><h3>Escalate Beyond It</h3><p>Change that exceeds the PM's remit gets escalated. A question like "is this project still the organization's strategic priority, and who owns it now that the acquisition has closed?" is not a decision for the project manager to make alone — it belongs to the sponsor or the steering committee. Escalation here is not failure and not buck-passing; it's the disciplined recognition that some decisions genuinely sit above the project, and surfacing them promptly through the proper channels is exactly what good governance looks like.</p></>}</motion.div>{tabsSeen.length===2&&!qTwo&&<button className="knowledge-check-cta" onClick={()=>setQuiz(q2)}><Target/> Start knowledge check <ArrowRight/></button>}</div><img className="governance-art" src={governance} alt="Operational changes remain with the PM while strategic questions rise to governance"/></div>}
 {page===4&&<div className="throughline"><p className="eyebrow">THE MODULE 3 THROUGHLINE</p><h2>The Module 3 Throughline</h2><p className="lede">Zoom all the way out, and this enabler closes a theme that has run through the entirety of Module 3 — one that's easy to miss lesson by lesson, but obvious once you see the whole arc.</p><img src={throughline} alt="Business need, vision, stakeholders, and organizational change connected across Module 3"/><button className="primary compact-cta" onClick={()=>setArc(true)}>{arc?"Module arc revealed":"Reveal the shared skill"}<Sparkles/></button>{arc&&<motion.div className="throughline-copy" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}}><p>A project manager is not just a planner of tasks. They are a reader of context and people. Initiation read the business need. Developing a common vision read what would unite the team around a shared destination. The stakeholder work read who mattered and what they actually expected, both stated and unstated. And this lesson reads the organizational culture and the changes moving through it. In every case, the underlying skill is identical: perceive the human and organizational reality accurately, then act deliberately within it. The alternative — being blindsided — is how genuinely capable project managers still fail. The manager who never assessed the culture is puzzled by resistance that was entirely predictable. The one who ignored the acquisition is overtaken by a change they could have evaluated and escalated well before it became a crisis.</p></motion.div>}</div>}
 {page===5&&<div className="exam change-exam"><img src={resolved} alt="A disrupted project timeline is deliberately rerouted and continues forward"/><div><p className="eyebrow">SYNTHESIS (EXAM LENS) · MODULE 3 COMPLETE</p><h2>One instruction sums up this entire enabler — and, in a real sense, the whole of Module 3.</h2><button className="primary compact-cta" onClick={()=>setDone(true)}>{done?"Module 3 complete":"Reveal the synthesis"}<Sparkles/></button>{done&&<><p className="exam-synthesis">When the organization shifts, evaluate before you react. Restructures, mergers, technology shifts, and strategy changes each affect a project differently — and each deserves the same two questions: how does this affect the project, and what action does it require? Manage the human side of change through stakeholder engagement and honest, steady communication. Treat resistance as information, not obstruction. And when a change raises a question that sits above your authority, escalate it through the governance paths you set at initiation, rather than absorbing a decision that was never yours to make alone.</p><h3>Exam-relevant enablers to remember:</h3><ul><li>Four change types: restructure, merger/acquisition, technology shift, strategy/leadership change — each answers "how does this affect the project?" and "what action does it require?"</li><li>Change management at the project level = stakeholder engagement (address resistance) + communication (reduce fear through honesty), under uncertainty</li><li>Manage within your authority; escalate what genuinely sits above it — escalation is good governance, not failure</li><li>This completes ECO Business Environment Task 7 — and with it, Module 3: perceive reality accurately, act deliberately within it</li></ul></>}</div></div>}
 </motion.section></AnimatePresence>{can&&<div className="anchor"><Check/> Interaction complete — continue when ready.</div>}<footer className="nav-footer"><button className="secondary-button" disabled={page===0} onClick={()=>setPage(page-1)}><ArrowLeft/> Previous</button><button className={`primary-button ${can?"unlocked":""}`} disabled={!can} onClick={next}>{page===5?"Continue to Module 4":"Continue"}<ArrowRight/></button></footer></article></section></main><AnimatePresence>{detail&&<Modal detail={detail} onClose={()=>setDetail(null)} onRead={()=>{if(page===0)setHeroRead(true);readDetail()}}/>}</AnimatePresence>{quiz&&<Quiz data={quiz} onFinish={()=>{if(quiz===q1)setQOne(true);else setQTwo(true);setQuiz(null)}}/>}</div>}
createRoot(document.getElementById("root")).render(<App/>);
